export const DATA_SOURCE = 'DATA_SOURCE';

export const LINES_REPOSITORY = 'LINES_REPOSITORY';
export const LOCATIONS_REPOSITORY = 'LOCATIONS_REPOSITORY';
export const LINES_LOCATIONS_REPOSITORY = 'LINES_LOCATIONS_REPOSITORY';
export const LINES_LOCATIONS_DEPARTURES_REPOSITORY =
    'LINES_LOCATIONS_DEPARTURES_REPOSITORY';
export const LINES_ROUTES_REPOSITORY = 'LINES_ROUTES_REPOSITORY';
export const USERS_REPOSITORY = 'USERS_REPOSITORY';
